# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Blogs
    url: blogs/
    weight: 20
  - name: AI Projects
    url: /#aiprojects
    weight: 30
    hasChildren: true
  - name: Available Products
    url: solutions/
    weight: 40
    hasChildren: true
  # sub-items
  - parent: AI Projects
    name: Data Visualization
    url: /#datavisualization
    weight: 20
  - parent: AI Projects
    name: Data Science
    url: /#DataScience
    weight: 30
  - parent: AI Projects
    name: Computer Vision
    url: /#ComputerVision
    weight: 40
  - parent: AI Projects
    name: NLP
    url: /#nlp
    weight: 50
  - parent: Available Products
    name: Notion
    url: /#notion
    weight: 10
