# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Blogs
    url: blogs/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
    hasChildren: true
  - name: Available Products
    url: solutions/
    weight: 40
  - name: About
    url: /about
    weight: 50
  # sub-items
  - parent: Projects
    name: Data Visualization
    url: /projects/datavisualization
    weight: 20
  - parent: Projects
    name: Data Science
    url: /projects/datascience
    weight: 30
  - parent: Projects
    name: Computer Vision
    url: /projects/computervision
    weight: 40
  - parent: Projects
    name: NLP
    url: /projects/nlp
    weight: 50
