# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Blogs
    url: blogs/
    weight: 15
  - name: AI Projects
    url: /#aiprojects
    weight: 20
    hasChildren: true
  - parent: AI Projects
    name: Data Visualization
    url: /#datavisualization
    weight: 30
  - parent: AI Projects
    name: Data Science
    url: /#DataScience
    weight: 35
  - parent: AI Projects
    name: Computer Vision
    url: /#ComputerVision
    weight: 40
  - parent: AI Projects
    name: NLP
    url: /#nlp
    weight: 50
<<<<<<< HEAD
  - name: Available Products
    url: solutions/
=======
  - name: Commercial Solutions
    url: /#solutions
>>>>>>> 640040957c463ac86174df63c1d13fbde01128d1
    weight: 30
